### PR TITLE
Refactor/errors

### PR DESCRIPTION
**Pull request by njanetos**
Uses preprocessor directives to avoid explicitly checking errors in code.

### CODE REVIEW

**Comment by njanetos** [comment]
Addressed #13.

**Comment by jtilly** [comment]
Looks great. The only downfall is that this creates compiler warnings of the sort:
```
warning: unused variable 'error_code' [-Wunused-variable]
    PetscErrorCode error_code;
```

**Comment by njanetos** [comment]
Hm, that's odd. It doesn't for me. Here's my compiler output:

```bash
R CMD INSTALL --preclean --no-multiarch --with-keep.source taoR

* installing to library ‘/home/njanetos/R/x86_64-pc-linux-gnu-library/3.2’
* installing *source* package ‘taoR’ ...
** libs
g++ -I/usr/share/R/include -DNDEBUG   -I"/home/njanetos/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"  -I/home/njanetos/programming/petsc/arch-linux2-c-debug/include -I/home/njanetos/programming/petsc/include -I/home/njanetos/programming/petsc/include/petsc/mpiuni -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++ -I/usr/share/R/include -DNDEBUG   -I"/home/njanetos/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"  -I/home/njanetos/programming/petsc/arch-linux2-c-debug/include -I/home/njanetos/programming/petsc/include -I/home/njanetos/programming/petsc/include/petsc/mpiuni -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c evaluate.cpp -o evaluate.o
g++ -I/usr/share/R/include -DNDEBUG   -I"/home/njanetos/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"  -I/home/njanetos/programming/petsc/arch-linux2-c-debug/include -I/home/njanetos/programming/petsc/include -I/home/njanetos/programming/petsc/include/petsc/mpiuni -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c tao.cpp -o tao.o
g++ -I/usr/share/R/include -DNDEBUG   -I"/home/njanetos/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"  -I/home/njanetos/programming/petsc/arch-linux2-c-debug/include -I/home/njanetos/programming/petsc/include -I/home/njanetos/programming/petsc/include/petsc/mpiuni -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c utils.cpp -o utils.o
g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o taoR.so RcppExports.o evaluate.o tao.o utils.o -Wl,-rpath,/home/njanetos/programming/petsc/arch-linux2-c-debug/lib -L/home/njanetos/programming/petsc/arch-linux2-c-debug/lib -lpetsc -llapack -lblas -lpthread -lm -lgfortran -lquadmath -lstdc++ -ldl -L/usr/lib/R/lib -lR
installing to /home/njanetos/R/x86_64-pc-linux-gnu-library/3.2/taoR/libs
** R
** demo
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (taoR)
```

**Comment by njanetos** [comment]
Because I don't have the `-Wunused-variable` flag set I suppose.

**Comment by njanetos** [comment]
The odd thing is that it _isn't_ an unused variable. It should be equivalent to the old way it was done.

**Comment by jtilly** [comment]
It's not used. The variable is freshly defined inside the pre-compiler constant every time it's used. Anyways, fixed it with 597ad84.

**Comment by njanetos** [comment]
...wait what is this i dont

It's used right after it's 'freshly defined'. 

lemon

And your fix just moved a bunch of lines around.

Oh ho ho ho ho I see what's going on here. You make a silly and now you're trying to hide the evidence. 

nicetry

Nice try.

**Pull request merged**
